title: Ben Ptacek
author: Ben Ptacek
email: ben.ptacek@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My site

# social links
github_username:  bennysp # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
